import { Injectable, BadRequestException } from '@nestjs/common';
import { DiaryPageDto } from './dto/diary-page.dto.js';
import { CreateDiaryPageDto, DiaryPageCreatedDto } from './dto/create-diary-page.dto.js';
import { db } from '../../drizzle/db.js';
import { paginaDiario } from '../../drizzle/schema.js';
import { eq, desc } from 'drizzle-orm';

@Injectable()
export class DiaryService {
    /**
     * Get all diary pages for a specific patient, ordered by date (most recent first)
     * @param patientId - The UUID of the patient
     * @returns Array of diary pages
     */
    async getDiaryPages(patientId: string): Promise<DiaryPageDto[]> {
        const pages = await db
            .select({
                id: paginaDiario.idPaginaDiario,
                title: paginaDiario.titolo,
                content: paginaDiario.testo,
                createdAt: paginaDiario.dataInserimento,
            })
            .from(paginaDiario)
            .where(eq(paginaDiario.idPaziente, patientId))
            .orderBy(desc(paginaDiario.dataInserimento));

        return pages.map(page => ({
            id: page.id,
            title: page.title,
            content: page.content,
            createdAt: page.createdAt || new Date(),
        }));
    }

    /**
     * Create a new diary page for a patient
     * @param patientId - The UUID of the patient
     * @param dto - Data for the new diary page (title, content)
     * @returns Confirmation with ID of the created diary page
     */
    async createDiaryPage(
        patientId: string,
        dto: CreateDiaryPageDto
    ): Promise<DiaryPageCreatedDto> {
        // Create DTO instance and validate
        const dtoInstance = Object.assign(new CreateDiaryPageDto(), dto);

        // Validate DTO
        const validationErrors = dtoInstance.validate();
        if (validationErrors.length > 0) {
            throw new BadRequestException(validationErrors.join(', '));
        }

        // Insert into pagina_diario table
        const inserted = await db
            .insert(paginaDiario)
            .values({
                idPaziente: patientId,
                titolo: dto.title.trim(),
                testo: dto.content.trim(),
                // dataInserimento is automatically generated by the database
            })
            .returning({ id: paginaDiario.idPaginaDiario });

        const id = inserted[0]?.id;

        if (!id) {
            throw new Error('Impossibile creare la pagina del diario');
        }

        return {
            success: true,
            id,
            message: 'Pagina del diario creata con successo',
        };
    }
}
